description: "Mechanical / Robotics Engineer"

url: "https://spanghal23.github.io"
baseurl: ""   # user site → keep this empty

remote_theme: "mmistakes/minimal-mistakes@4.27.3"
minimal_mistakes_skin: "dark"

plugins:
  - jekyll-include-cache

# --- Author profile (shows in sidebar if author_profile: true) ---
author:
  name: "Sameer Panghal"
  avatar: "/assets/images/avatar.jpg"   # change or remove if you don't have this image
  bio: ""
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/spanghal23"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "www.linkedin.com/in/sameerpanghal"

# --- Defaults so you don't have to repeat layout everywhere ---
#defaults:
#  - scope:
#      path: ""
#      type: "posts"
#    values:
#      layout: "single"
#      author_profile: true
